services:
  - type: web
    name: sentiment-analysis-flask
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python -c "import nltk; nltk.download('stopwords')"
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
